### ISSUE TITLE
You should never show secret ID of an app

### ISSUE THREAD

**Issue by Cicko** [Psvensso/HotRobe#1]
There: [link](https://github.com/Psvensso/HotRobe/blob/aa632db57feda0917ad5baeeb361e018e5204f1a/server/config/auth/providers/github.js#L6)

You are showing the client Secret and its very dangerous. You should put it in environment variable to avoid publication of it on internet.

**Comment by Psvensso** [comment]
Thanks for pointing out, 
this secret is deactivate a long time ago though :)
I never leave or enter actual app secrets in source.

**Comment by Psvensso** [comment]
Deactivated.
